- job:
    name: ansible-role-grafyaml
    run: tests/test.yaml
    roles:
      - zuul: openstack/ansible-role-grafyaml

- job:
    name: ansible-role-grafyaml-fedora-latest
    parent: ansible-role-grafyaml
    nodeset: fedora-latest

- job:
    name: ansible-role-grafyaml-ubuntu-bionic
    parent: ansible-role-grafyaml
    nodeset: ubuntu-bionic

- project:
    check:
      jobs:
        - ansible-role-grafyaml-fedora-latest
        - ansible-role-grafyaml-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-grafyaml-fedora-latest
        - ansible-role-grafyaml-ubuntu-bionic
        - tox-linters
