- job:
    name: ansible-role-grafyaml
    run: tests/test.yaml
    roles:
      - zuul: openstack/ansible-role-grafyaml

- job:
    name: ansible-role-grafyaml-fedora-latest
    parent: ansible-role-grafyaml
    nodeset: fedora-latest

- job:
    name: ansible-role-grafyaml-ubuntu-bionic
    parent: ansible-role-grafyaml
    nodeset: ubuntu-bionic

- job:
    name: ansible-role-grafyaml-ubuntu-xenial
    parent: ansible-role-grafyaml
    nodeset: ubuntu-xenial

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
      - windmill-jobs-xenial
    check:
      jobs:
        - ansible-role-grafyaml-fedora-latest
        - ansible-role-grafyaml-ubuntu-bionic
        - ansible-role-grafyaml-ubuntu-xenial
        - tox-linters
    gate:
      jobs:
        - ansible-role-grafyaml-fedora-latest
        - ansible-role-grafyaml-ubuntu-bionic
        - ansible-role-grafyaml-ubuntu-xenial
        - tox-linters
